[package]
name = "emojipicker"
version = "0.1.0"
edition = "2021"

[dependencies]
relm4 = "0.9.0"
gtk = { version = "0.9.0", package = "gtk4"}
tracker = "0.2.2"
emojis = "0.6.3"
tokio = { version = "1", features = ["full"] }
